sudo: false

language: java

jdk: oraclejdk7

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/build-artifacts"

env:
  matrix:
  - DISPLAY=:99.0
  global:
    secure: VhTSeBNJTB3+qNhVAHnROTbSPDwV73PpSYQ2oF2YBXA1Bp406qE4iqSydhdDi5UaScZkEC1SJatzja+NESjUvxjHt3MAn8oQeA0OuSz6Isxwq0btxaF00ZBwxUQXBPsNz4OfJTErvxfzifdFtcadZGPzlk8HeNvKXSZ+AMGIBs2GUO+g3+/AMlDiBDgPkby5XcvhN0QBpKwqa9Y8/0puXPNum201VxVrV3W7Of89B7aV5zSYIdU8432Rkz0BkH5VU9yXC2T8FCZ06KaUkY1iXxSnswtzX07EZXgws91nsyDYr5sFm5uy2MwUflOAW9SpFQmHsXBVArEhwiASgdYDSSxDUyCcpJkq5woWw8HD+vY3QHl++r1NbJlK4xkZKWwXmEKxjw/Aj17zPpiQ03lGnTeMvrgrM1IhjmcuYAbgFpRraoz+aKrmHfNOTbXixWzp9H8mY/HPl/hCiuT/dX7rgmMbOnJ0wWLkwfIS1nYjNCRAhX1zUR0JLB3l/05NT0+f05lrwe+p0hdyjrtMKCUh0qqUwbarME/T6BpaUM02L9rjEjTM9uDRUfL7vN/OaxjhzMbUVTyx/ItmBAMBR7gAnqrXLDdghkEalOHWdIMQtxGuQNEEMznLuvpbV5SUgrIlSl6z237zVapRky5yU3wLogclt4QG3VPZE+tNMoeFiI0=

install: true

addons:
  apt:
    packages:
    - metacity

before_script:
- sh -e /etc/init.d/xvfb start
- metacity --sm-disable --replace 2> metacity.err &

script:
- export
- mvn clean verify

after_script:
- ./push-build-artifacts.sh
